application: your-application-id
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: 2.6
- name: markupsafe
  version: latest

handlers:
- url: /static
  static_dir: static
  login: required
  secure: always

- url: /admin/proxy/.*
  script: controllers.admin.app
  login: admin
  secure: always

- url: /admin.*
  script: controllers.owner.app
  login: required
  secure: always

- url: /.*
  script: controllers.public.app
  secure: optional
